syntax = "proto3";

package enrollment;

service EnrollmentService {
  rpc CreateEnrollment(CreateEnrollmentRequest) returns (EnrollmentResponse);
  rpc ListEnrollmentsByStudent(ListEnrollmentsByStudentRequest) returns (ListEnrollmentsByStudentResponse);
  rpc ListStudentCourseIds(ListStudentCourseIdsRequest) returns (ListStudentCourseIdsResponse);
  rpc ListCourseStudentIds(ListCourseStudentIdsRequest) returns (ListCourseStudentIdsResponse);
}

message Enrollment {
  string id = 1;
  string student_id = 2;
  string course_id = 3;
  string status = 4;
}

message CreateEnrollmentRequest {
  string student_id = 1;
  string course_id = 2;
}

message EnrollmentResponse {
  Enrollment enrollment = 1;
}

message ListEnrollmentsByStudentRequest {
  string student_id = 1;
}

message ListEnrollmentsByStudentResponse {
  repeated Enrollment enrollments = 1;
}

message ListStudentCourseIdsRequest {
  string student_id = 1;
}

message ListStudentCourseIdsResponse {
  repeated string course_ids = 1;
}

message ListCourseStudentIdsRequest {
  string course_id = 1;
}

message ListCourseStudentIdsResponse {
  repeated string student_ids = 1;
}
